export type Material = "wood" | "metal" | "paper" | "electronic" | "cloth";

export interface Product {
    slug: string;
    name: string;
    price: number;
    unit: string;
    mat: Material;
    cat: string;
    icon: string;
    moq: number;
    specs: Record<string, string>;
    description?: string;
    // Replace these with actual image paths in /public/images/
    imagePlaceholder: string;
}

export const products: Product[] = [
    {
        slug: "bhatia-battery-of-intelligence",
        name: "Bhatia Battery of Intelligence",
        price: 5500,
        unit: "Piece",
        mat: "paper",
        cat: "Intelligence Test",
        icon: "📋",
        moq: 1,
        imagePlaceholder: "/product/bhatia-battery-of-intelligence.png",
        description:
            "A comprehensive performance test of intelligence comprising multiple sub-tests. Widely used in industrial and laboratory settings for psychological assessment.",
        specs: {
            "Equipment Type": "Psychological",
            Application: "Industrial, Laboratory",
            "Automation Grade": "Manual",
            Color: "Black",
            Condition: "New",
            Material: "Cardboard",
            "Product Type": "Bhatia Battery",
            Shape: "Rectangle",
            Size: "Standard",
            Technology: "Paper-pencil",
            "Treatment Type": "Psychological assessment",
        },
    },
    {
        slug: "sfbt",
        name: "Seguin Form Board Test (SFBT)",
        price: 2500,
        unit: "Unit",
        mat: "wood",
        cat: "Form Board",
        icon: "🔲",
        moq: 1,
        imagePlaceholder: "/product/SFBT.png",
        specs: {
            Application: "Industrial, Laboratory",
            Condition: "New",
            Material: "Wood",
            "Product Type": "Seguin Form Board Test",
            Shape: "Rectangle",
            Size: "Standard",
            Warranty: "1 Year",
        },
    },
    {
        slug: "weight-discrimination",
        name: "Weight Discrimination",
        price: 2500,
        unit: "Piece",
        mat: "wood",
        cat: "Sensory Test",
        icon: "⚖️",
        moq: 1,
        imagePlaceholder: "/product/Weight_Discrimination.png",
        specs: {
            Application: "Industrial, Laboratory",
            Material: "Wood",
            "Product Type": "Weight Discrimination",
        },
    },
    {
        slug: "muller-lyer-illusion",
        name: "Muller Lyer Illusion",
        price: 2500,
        unit: "Piece",
        mat: "metal",
        cat: "Perception",
        icon: "📐",
        moq: 1,
        imagePlaceholder: "/product/Muller_Lyer_Illusion.png",
        specs: {
            Application: "Psychology Laboratory",
            "Color Code": "White & Brown",
            Material: "Metal & Wooden",
            "Product Type": "Muller Lyer Illusion",
            Weight: "3 Kilograms",
            "Suitable For": "Practical purpose",
        },
    },
    {
        slug: "metronome-electronics",
        name: "Metronome Electronics",
        price: 6500,
        unit: "Piece",
        mat: "electronic",
        cat: "Electronic",
        icon: "🔊",
        moq: 1,
        imagePlaceholder: "/product/Metronome_Electronics.png",
        specs: {
            Application: "Industrial, Laboratory",
            "Color Code": "Black & Blue",
            Material: "Wooden & Electrical",
            Power: "6 Volt",
            "Product Type": "Metronome Electronics",
            Weight: "1 Kilogram",
        },
    },
    {
        slug: "kohs-block-design-test",
        name: "Kohs Block Design Test",
        price: 2500,
        unit: "Unit",
        mat: "wood",
        cat: "Intelligence Test",
        icon: "🧩",
        moq: 1,
        imagePlaceholder: "/product/Kohs_Block_Design_Test.png",
        specs: {
            Application: "Industrial, Laboratory",
            Condition: "New",
            Material: "Wood",
            "Product Type": "Kohs Block Design Test",
            Shape: "Rectangle",
            Size: "Standard",
            Warranty: "1 Year",
        },
    },
    {
        slug: "rational-learning-apparatus",
        name: "Rational Learning Apparatus",
        price: 7000,
        unit: "Piece",
        mat: "metal",
        cat: "Learning",
        icon: "🔬",
        moq: 1,
        imagePlaceholder: "/product/Rational_Learning_Apparatus.png",
        specs: {
            Application: "Industrial, Laboratory",
            "Color Code": "Black",
            Condition: "New",
            Material: "Metal",
            "Product Type": "Rational Learning Apparatus",
            Shape: "Rectangle",
            Warranty: "1 Year",
        },
    },
    {
        slug: "conflict-board",
        name: "Conflict Board",
        price: 6500,
        unit: "Piece",
        mat: "metal",
        cat: "Behaviour",
        icon: "🎯",
        moq: 1,
        imagePlaceholder: "/product/Conflict_Board.png",
        specs: {
            Application: "Industrial, Laboratory",
            "Color Code": "Black",
            Material: "Metal",
            "Product Type": "Conflict Board",
            Size: "Standard",
        },
    },
    {
        slug: "horizontal-vertical-illusion",
        name: "Horizontal Vertical Illusion",
        price: 2200,
        unit: "Piece",
        mat: "metal",
        cat: "Perception",
        icon: "➕",
        moq: 1,
        imagePlaceholder: "/product/Horizontal_Vertical_Illusion.png",
        specs: {
            Application: "Industrial, Laboratory",
            "Color Code": "White & Black",
            Material: "Wood & Metal",
            "Product Type": "Horizontal Vertical Illusion",
            Weight: "3 Kilograms",
        },
    },
    {
        slug: "pass-along-test",
        name: "Pass Along Test",
        price: 2000,
        unit: "Unit",
        mat: "wood",
        cat: "Performance Test",
        icon: "🪵",
        moq: 1,
        imagePlaceholder: "/product/Pass_Along_Test.png",
        specs: {
            Application: "Laboratory",
            Material: "Wood",
            "Product Type": "Pass Along Test",
            "Suitable For": "Psychology students",
            Weight: "1 Kilogram",
        },
    },
    {
        slug: "marked-unmarked-ruler",
        name: "Marked Unmarked Ruler",
        price: 150,
        unit: "Piece",
        mat: "wood",
        cat: "Measurement",
        icon: "📏",
        moq: 1,
        imagePlaceholder: "/product/Marked_Unmarked_Ruler.png",
        specs: {
            Application: "Psychology labs",
            "Color Code": "White & Brown",
            Material: "Wooden",
            "Product Type": "Marked Unmarked Ruler",
            Use: "Practical purpose",
        },
    },
    {
        slug: "tachistoscope-falling-door",
        name: "Tachistoscope Falling Door",
        price: 2500,
        unit: "Piece",
        mat: "metal",
        cat: "Attention",
        icon: "🚪",
        moq: 1,
        imagePlaceholder: "/product/Tachistoscope_Falling_Door.png",
        specs: {
            Application: "Psychology Laboratory",
            "Color Code": "Silver & Black",
            Material: "Wooden, Aluminum",
            "Product Type": "Tachistoscope Falling Door",
            Use: "To measure span of attention",
        },
    },
    {
        slug: "blind-folds",
        name: "Blind Folds",
        price: 150,
        unit: "Piece",
        mat: "cloth",
        cat: "Accessory",
        icon: "👁️",
        moq: 1,
        imagePlaceholder: "/product/Blind_Folds.png",
        specs: {
            Application: "Psychology Laboratory",
            "Color Code": "Blue",
            Material: "Cloth",
            "Product Type": "Blind Folds",
        },
    },
    {
        slug: "wooden-screen",
        name: "Wooden Screen",
        price: 400,
        unit: "Piece",
        mat: "wood",
        cat: "Accessory",
        icon: "🪟",
        moq: 1,
        imagePlaceholder: "/product/Wooden_Screen.png",
        specs: {
            Application: "Industrial, Laboratory",
            Material: "Wood",
            "Product Type": "Wooden Screen",
        },
    },
    {
        slug: "habit-interference-board",
        name: "Habit Interference Board",
        price: 900,
        unit: "Piece",
        mat: "metal",
        cat: "Learning",
        icon: "🔀",
        moq: 1,
        imagePlaceholder: "/product/Habit_Interference_Board.png",
        specs: {
            Application: "Industrial, Laboratory",
            Material: "Wood, Metal",
            "Product Type": "Habit Interference Board",
        },
    },
    {
        slug: "mcduggle-disc-apparatus",
        name: "McDuggle Disc Apparatus",
        price: 1250,
        unit: "Piece",
        mat: "metal",
        cat: "Apparatus",
        icon: "💿",
        moq: 1,
        imagePlaceholder: "/product/McDuggle_Disc_Apparatus.png",
        specs: {
            Application: "Industrial, Laboratory",
            Material: "Wood, Metal",
            "Product Type": "McDuggle Disc Apparatus",
        },
    },
    {
        slug: "mirror-drawing-paper-star",
        name: "Mirror Drawing Paper Star",
        price: 2000,
        unit: "Unit",
        mat: "paper",
        cat: "Motor Skill",
        icon: "⭐",
        moq: 1,
        imagePlaceholder: "/product/Mirror_Drawing_Paper_Star.png",
        specs: {
            Application: "Industrial, Laboratory",
            Material: "Wood, Metal",
            "Product Type": "Mirror Drawing Paper Star",
        },
    },
    {
        slug: "mirror-drawing-metal-star",
        name: "Mirror Drawing Metal Star Electronics",
        price: 6500,
        unit: "Piece",
        mat: "electronic",
        cat: "Motor/Electronic",
        icon: "✨",
        moq: 1,
        imagePlaceholder: "/product/Mirror_Drawing_Metal_Star_Electronics.png",
        specs: {
            Application: "Industrial, Laboratory",
            Material: "Wood, Metal",
            "Product Type": "Mirror Drawing Metal Star Electronics",
        },
    },
    {
        slug: "error-counter-6-digits",
        name: "Error Counter 6 Digits",
        price: 2500,
        unit: "Unit",
        mat: "metal",
        cat: "Counter",
        icon: "🔢",
        moq: 1,
        imagePlaceholder: "/product/Error_Counter_6_Digits.png",
        specs: {
            Application: "Industrial, Laboratory",
            Material: "Metal",
            "Product Type": "Error Counter 6 Digits",
        },
    },
    {
        slug: "steadiness-tester",
        name: "Steadiness Tester",
        price: 2500,
        unit: "Piece",
        mat: "metal",
        cat: "Motor Skill",
        icon: "🎯",
        moq: 1,
        imagePlaceholder: "/product/Steadiness_Tester.png",
        specs: {
            Application: "Medical Industries",
            Material: "Wood, Metal",
            "Product Type": "Steadiness Tester",
        },
    },
    {
        slug: "bolt-head-maze",
        name: "Bolt Head Maze with Error Counter",
        price: 550,
        unit: "Unit",
        mat: "metal",
        cat: "Maze Test",
        icon: "🌀",
        moq: 1,
        imagePlaceholder: "/product/Bolt_Head_Maze_with_Error_Counter.png",
        specs: {
            Application: "Industrial, Laboratory",
            Material: "Metal",
            "Product Type": "Bolt Head Maze",
        },
    },
    {
        slug: "personality-psychosocial-behaviour",
        name: "Personality & Psychosocial Behaviour (English)",
        price: 800,
        unit: "Piece",
        mat: "paper",
        cat: "Book",
        icon: "📘",
        moq: 1,
        imagePlaceholder: "/product/Personality_and_Psychosocial_Behaviour.png",
        specs: {
            "Color Code": "Black",
            Material: "Cardboard",
            "Product Type": "Psychology Book",
        },
    },
    {
        slug: "risk-taking-personality",
        name: "Risk Taking And Personality (English)",
        price: 450,
        unit: "Piece",
        mat: "paper",
        cat: "Book",
        icon: "📕",
        moq: 1,
        imagePlaceholder: "/product/Risk_Taking_And_Personality.png",
        specs: {
            "Color Code": "Red Black",
            "Product Type": "Personality Development Book",
        },
    },
    {
        slug: "self-concept-scale",
        name: "Self Concept Scale",
        price: 1250,
        unit: "Piece",
        mat: "paper",
        cat: "Scale",
        icon: "📊",
        moq: 1,
        imagePlaceholder: "/product/Self_Concept_Scale.png",
        specs: {
            Material: "Paper",
            "Product Type": "Self Concept Scale",
        },
    },
    {
        slug: "manasshastrachi-multatwe",
        name: "Manasshastrachi Multatwe (Marathi)",
        price: 150,
        unit: "Piece",
        mat: "paper",
        cat: "Book",
        icon: "📗",
        moq: 100,
        imagePlaceholder: "/product/Manasshatrachi_Multatwe_Marathi.png",
        specs: {
            "Product Type": "Psychology Book",
            "Suitable For": "Psychological Therapies",
        },
    },
];